### ISSUE TITLE
某A事務所用カスタマイズについての質問

### ISSUE THREAD

**Issue by gamasenninn** [Crescom-SohoCaddie/soho-caddie#1014]
●請求書明細の項目に「日付」がある。DBには当該カラムは存在しない。どうするか？

案1:　任意番号に日付を入力できるようにする。しかし、任意番号はユニーク項目であり、かつ数値である。また、任意番号はソートの役割が強い（？）ため、目的が異なる。

案2:　現時点でもっとも自然なのは、内容を入力するときに「日付 内容」とし、日付も内容の一部として扱う。

案3:　DBに「自由項目」（文字列）を追加し、用途は自由とする。画面で自由項目を入力できるようにする。

![image_xx](https://user-images.githubusercontent.com/61409504/162869442-ae40d610-5bb4-428a-818e-86b2cb0df139.png)

**Comment by gamasenninn** [comment]
自由項目は存在した。日付の入力も可能なので、そのカラムで対応する。

**Comment by crescom-ohira** [comment]
案3で大丈夫かなと思います。
よろしくお願いします。
