### ISSUE TITLE
やるべきとこはISSUEにあげてね。

### ISSUE THREAD

**Issue by gamasenninn** [Crescom-SohoCaddie/soho-caddie#1025]
プロジェクト参加者各位。メッセンジャーだけではなにをすればわからんので、タスクにする必要があるものは、かならずISSUEにあげてください。メッセンジャーはあくまで議論なので、それをやるかどうかは、ISSUEにあげて参加者全員で情報を共有する必要があります。このへん徹底してね。

**Comment by monomonosu** [comment]
御意。

**Comment by gamasenninn** [comment]
カスタマイズなど個別対応するものは、さまざまな機密事項があると思うので、その場合はメッセンジャーやSLACKなどでもOK。理想的には共有ファイルが理想だけどね。

**Comment by gamasenninn** [comment]
逆にいうと、ISSUEに上がっていないタスクはやらない。というルールにしよう。

**Comment by crescom-ohira** [comment]
了解しました。

**Comment by gamasenninn** [comment]
全員に周知完了なので、このISSUEクローズします。
