### ISSUE TITLE
領収書のレイアウト

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1026]
![image](https://user-images.githubusercontent.com/77572073/163326876-ce92e9b8-14d8-48c2-9a86-2ae6f53b712b.png)

![image](https://user-images.githubusercontent.com/77572073/163326659-0b295c07-73d3-4621-8e65-8ee2f37829f1.png)

**Comment by gamasenninn** [comment]
入金区分とか入ってないよ。どうする？

**Comment by monomonosu** [comment]
入金区分は絶対ではないとの事。
入ってないのもあるとの事。

![image](https://user-images.githubusercontent.com/77572073/163328540-817441c9-282a-4b07-ae16-b818d67529f2.png)

**Comment by monomonosu** [comment]
![image](https://user-images.githubusercontent.com/77572073/163328965-e0b2eba9-ca34-4f5c-83b1-eb70911db06f.png)

**Comment by crescom-ohira** [comment]
入金区分はSohoLifeでもなかったので、今回はなしでいきましょう。
もしかすると今後お客様から希望される声が上がってくる可能性もあるかとおもいますので、その際は検討したいと思います。

**Comment by gamasenninn** [comment]
了解。
