### ISSUE TITLE
カスタマイズ用プライベートリポジトリを作成

### ISSUE THREAD

**Issue by gamasenninn** [Crescom-SohoCaddie/soho-caddie#1028]
https://github.com/Crescom-SohoCaddie/caddie-customを作成しました。
ユーザごとのディレクトリに分かれています。
customizeフォルダーに個別ファイルを保存する形になります。
とりあえずこれで運用してみて、改善していきましょう。
どんどんアイディアくださいね。

**Comment by monomonosu** [comment]
URLに「を作成しました」が含まれてる件。
こっちだな。
https://github.com/Crescom-SohoCaddie/caddie-custom

**Comment by crescom-ohira** [comment]
customizeフォルダーに個別ファイルで対応できるのは便利ですね。
今後、運用していきながら使い勝手など検証していきます。

**Comment by gamasenninn** [comment]
とりあえず、運用していきながら改善するという方向性で決定なので、このISSUEはクローズします。
