### ISSUE TITLE
A事務所カスタマイズ。必要な帳票は？

### ISSUE THREAD

**Issue by gamasenninn** [Crescom-SohoCaddie/soho-caddie#1032]
請求書は必要なのは自明だが、その他必要なのは？

・納品書
・請求書控え
・納品書
・領収書
・見積書

これら選択に伴い、印刷ボタンの選択カスタマイズが必要かもしれない。そのためには印刷ボタンのコンポ化も必要かも。

**Comment by crescom-ohira** [comment]
先方に確認したところ、請求書のみあれば大丈夫とのことです。

**Comment by gamasenninn** [comment]
了解です。

**Comment by gamasenninn** [comment]
カスタマイズにより、請求書は請求のみ。見積書は印刷ボタンを非表示にしました。

**Comment by crescom-ohira** [comment]
了解しました。
ありがとうございます。
確認してみます。
