### ISSUE TITLE
ロゴ・印鑑のアップロードに削除ボタンを追加

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1036]
各種設定→会社情報のロゴ・印鑑アップロードの項目に削除ボタンを設けて欲しいとの事。
削除ボタンを押した後のアクションはどうするか。
請求書に載せるロゴ・印鑑の表示を完全に無くすのか。それともデフォルトで設定されているロゴ・印鑑に設定を戻すのか。
もう少し仕様を詰める必要がありそう。

- [x] フロントに削除ボタン付与
- [x] 削除ロジック追加
- [x] ファイルがなければ、Noimg表示

**Comment by monomonosu** [comment]
表示を無くすようにする

**Comment by gamasenninn** [comment]
削除ボタンだけフロントにつけておいて＞monomonosu

**Comment by monomonosu** [comment]
@gamasenninn 
御意

**Comment by monomonosu** [comment]
ロゴ・印鑑の削除ボタンは追加した。

**Comment by monomonosu** [comment]
@gamasenninn 
これ、できそうなので消化してしまう。
