### ISSUE TITLE
GitHub上のデフォルトブランチをdevelopに。mainを削除できないように。

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1037]
デフォルトのブランチがmainのままだとプルリクを出すときにmerge先を間違えやすくなるので、デフォルトブランチをdevelopに変更する。
さらに、誤ってmainブランチを削除してしまわないように設定を変更してみる。

個人でテスト的にリポジトリを立てて、そこで問題なければsoho-caddieに反映をしてみる。

**Comment by monomonosu** [comment]
リポジトリのsettingはリポジトリの管理者じゃないと変更できないようなので、後日やる。

**Comment by gamasenninn** [comment]
monomonosuをこのリポの管理者にしてください。

**Comment by crescom-ohira** [comment]
管理者に変更しました。

**Comment by gamasenninn** [comment]
ありがとうございます。
