### ISSUE TITLE
T法人向けの請求書レイアウト変更。

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1041]
T法人向けの請求書のカスタマイズレイアウトを変更する。

- [ ] 客先出力欄（〇〇御中）は文字が長くなっても改行せずに、文字のフォントを変更しながら１行になるようにする。
- [ ] 明細欄は明細項目が増えるごとに外線を引く形式から、元々あるフォーマットに直接値を当てはめていく方式に変更する。

@crescom-ohira 
２つめの実装に関して、明細が１行で１件なら問題なく実装できそうです。
しかしながら少々問題があり質問なのですが、
２行で１件の明細項目が混じると出力文字にズレが発生するかと思われるのですがこれはどうしましょう？

**Comment by monomonosu** [comment]
T法人では明細が２行になるような事は無いとの事。
なので１行で１件として考えて、フォーマットに値を埋め込んでいく方式とする。

**Comment by monomonosu** [comment]
@crescom-ohira 

@gamasenninn との話し合いで、明細に合計欄を追従できるとの事なので、埋め込み方式ではなく外線を引く方式の方が良さそうです。
請求書２ページになっちゃうよ問題は、T法人の方では改行を行わない。との事だったので、問題はなさそうですので外線を引く方式に変更しようと思うのですがどうでしょう？

**Comment by crescom-ohira** [comment]
外線を引く方法で大丈夫です。

**Comment by crescom-ohira** [comment]
例えば今後改行や項目が多く２ページ以上になってしまうクライアント様がでてきた場合、1ページ用と複数ページ用のフォーマットを作って1ページに収まらなかった場合には複数ページ用のフォーマットに切り替わるみたいなやり方はできますか？

**Comment by gamasenninn** [comment]
２ページ以降別フォーマット方式。たぶんできると思う。２ページは別ベースを表示するようにロジック組めばいいかな。とりあえず、できる方針で考えてもらってOK。

**Comment by crescom-ohira** [comment]
いま使用しているSohoLifeの場合は項目数が多くなるとこんな感じのフォーマットになります。
[テスト.pdf](https://github.com/Crescom-SohoCaddie/soho-caddie/files/8518188/default.pdf)

**Comment by gamasenninn** [comment]
フォーマットの概要はわかりました。だが、これはかなりハードな実装になりそう。一旦印刷してみないと溢れは検知できない。かなり行き当たりバッタりなロジックになりそうだね。もし、既定行数が多くなったら、複数ページ。という仕様ならば対応可能かと。

**Comment by crescom-ohira** [comment]
了解です。
では複数ページで出る仕様でいきたいと思います。

**Comment by gamasenninn** [comment]
既定行数（例えば15行）を越えたら、別フォーマットの複数ページを出力。という仕様でいいですね？

**Comment by gamasenninn** [comment]
術式的にいうと、PDF生成前に明細データ件数をカウントして既定行数以内なら通常フォーマットを用い、既定行数を越えたら、複数ページフォーマットを用いる。

**Comment by gamasenninn** [comment]
レスポンスがないようなので、とりあえず、上記の仕様で行きます。このISSUEはクローズします。
