### ISSUE TITLE
ログアウトをするとページが見つかりませんとなってしまう

### ISSUE THREAD

**Issue by crescom-ohira** [Crescom-SohoCaddie/soho-caddie#1043]
ログアウトをするとページが見つかりませんとなってしまう
![bug](https://user-images.githubusercontent.com/97567597/164175098-dff606b4-6a29-4727-99b8-63da495b213f.png)

**Comment by monomonosu** [comment]
30分後のセッションタイムアウト後にこれが出るらしい

**Comment by monomonosu** [comment]
デモ環境でNotFoundが出ない事を確認。
