### ISSUE TITLE
T法人向け請求書のレイアウト修正。

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1050]
- [x] 得意先名は最大文字数を１５文字と考え、１行に収まるようにする。得意先名と敬称は同じ文字列にせずに別々に要素を分けて、敬称のみが改行れないような形にする。
- [x] 日付の内容が左揃えになっているので、中央揃えにする。
- [x] 明細欄と上の欄（合計金額・会社情報欄）の幅が若干違うので幅を合わせる。
- [x] 備考（？）が書いてある欄が、１行目と２行目でズレがあるので、幅を合わせる

![image](https://user-images.githubusercontent.com/77572073/164389696-75a30192-64e7-4aa5-9147-aa07efd18e92.png)

**Comment by gamasenninn** [comment]
＞備考（？）が書いてある欄が、１行目と２行目でズレがあるので、幅を合わせる
この馬鹿みたいな修正で、セルを追加して※だけ独立させなければならない。ロジックはたいして難しいものではないが、プログラムは目に見えて複雑になるり、あとから修正する人が戸惑うもとになる。こういった微調整はやらなくてよいもたいして影響のないものは時間の無駄なのでできるだけトリアージしてほしい＞ohira

**Comment by gamasenninn** [comment]
カスタマイズリポにプルリクあげたよ＞monomonosu
