### ISSUE TITLE
ポートがふさがっていてもメンテナンス可能な方法を考える。

### ISSUE THREAD

**Issue by gamasenninn** [Crescom-SohoCaddie/soho-caddie#1069]
基本はquickconnectを使用し、ファイル更新は可能。
問題はアプリのテストができない。
そのための方法を考える。

１．無難なところで、かつ王道。VPN。
２.   SSHポートフォワード

**Comment by gamasenninn** [comment]
ちなみに、コンテナ内部にはすでにsshがインストールされているので、単にコマンドを編み込むだけでよい。windows側のsshでポートFWの実験はOK。

**Comment by gamasenninn** [comment]
@monomonosu というわけでこの方式でいくことになりました。

**Comment by monomonosu** [comment]
@gamasenninn 
synologyのGUI操作画面から内部でSSHが操作できるといったイメージで合ってる？
もしそうであればそのSSHから git clone さえできれば何も問題なさそうだな。

**Comment by gamasenninn** [comment]
@monomonosu 
ちょい違う。あくまで今回はコンテナの中のシェルを使って踏み台に対してトンネルを掘るイメージ。
トンネル技術はいつか教えようとしていたものなので、この機会にじっくり教えるね。

**Comment by monomonosu** [comment]
@gamasenninn 
それをするためにはまず、トンネルを掘るためのコンテナを立ち上げる必要が出てくる？
コンテナ立ち上げのためにdocker buildする必要が出てきそうだけどsynologyのDockerGUIツールはコマンド操作無しでもimageの作成ができる感じ？

**Comment by gamasenninn** [comment]
@monomonosu 
caddieコンテナ内のshellを使う。Docker GUIでctaddieを選択し、端末を使う。作成でbasshを選べば、bash使えるだろ。

**Comment by monomonosu** [comment]
@gamasenninn 
コンテナが立ち上がっていれば確かにbashを使えるが、そのコンテナ自体の立ち上げにコマンド操作が必要になってくるよね？
そのコマンド操作を行うのはSynologyOSの機能として元々備わっているのか？

**Comment by gamasenninn** [comment]
@monomonosu 
なるほど一番最初のステップのことか。最初はCaddieがインストールされてないもんな。なので、最初にssh付きの適当なコンテナをDocker GUIでロードして実行する。そのあと、GUIでそのコンテナのbashたちあげて、本体にssh接続し、dockerコマンドを叩いてCaddieをインストールする。

Caddieコンテナが動いたら、GUIのbashたちあげて踏み台サーバにsshせ接続。ポートを仮に9001だとすると、
`ssh -R 9001:localhost:80 <サーバのアドレス>`
でトンネルが開通する。

**Comment by gamasenninn** [comment]
というわけで、だいたいわかったと思うので、このISSUEはクローズする。
