### ISSUE TITLE
A事務所 帳票微調整

### ISSUE THREAD

**Issue by crescom-ohira** [Crescom-SohoCaddie/soho-caddie#1070]
この帳票への変更をお願いします。
「御請求書」の文字が少しだけ上になりました。
![base](---https://user-images.githubusercontent.com/97567597/165884650-2c303224-00a7-4dfe-bbd6-00d4102cc215.png)

**Comment by gamasenninn** [comment]
カスタムのほうに修正をあげておいた > @monomonosu 

https://github.com/Crescom-SohoCaddie/caddie-custom/pulls

**Comment by monomonosu** [comment]
@gamasenninn 
承認しますた。

**Comment by crescom-ohira** [comment]
ありがとうございます。

**Comment by gamasenninn** [comment]
というわけでこのISSUEはクローズします。
