### ISSUE TITLE
請求書の一括出力機能実装

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1100]
請求書を一括で出力できる機能を実装する。※請求書のみでOK
請求書一覧画面で請求書を複数選択可能な状態にして、一括印刷できるようにする。
さらに一括印刷する請求書の明細は、詳細に品名が書かれたものと、簡易的に省略されたものの2択で選択できるようにする。
こんな感じにして欲しい。との事。

【詳細に品名が書かれたもの】

![image](https://user-images.githubusercontent.com/77572073/168194699-4b05825b-3574-46c8-b2ad-4945b603661c.png)

【簡易的に省略されたもの】

![image](https://user-images.githubusercontent.com/77572073/168195392-be785a3d-12ee-4bb8-99b5-aca13e4d5065.png)

**Comment by monomonosu** [comment]
@gamasenninn 
PDFの作成の部分は正直よくわからないので、PDFに渡すデータの整形だけでもやろうと思う。
複数選択された請求書を構造体として出力できるようなメソッドを作成すれば良いだろうか？例えば
{ id:1,
 invoice_items:{ itemName:'商品',count:1,price:100 }
}
{ id:2,
 invoice_items:{ itemName:'商品',count:3,price:50 }
}
みたいな感じで

**Comment by gamasenninn** [comment]
やってほしいことは、データの成形よりも、一括処理の画面イメージの仕様決定と実装だね。現在の一覧を使いたい場合は明細行のどこかに選択用のチェックボックスを表示する。選択されたら、一括印刷ボタンなどで出力できるようにする。とか。
特殊ねケースなので一括処理用の画面を別につくってもいい。そのへんの仕様決定だね。

**Comment by monomonosu** [comment]
確かにチェックボックスは必要になりそうだな。
その辺ちゃんと決める必要がありそうだ。

**Comment by gamasenninn** [comment]
それと、一括請求は顧客単位なので、必ず顧客を選択してから一覧表示となる。日付範囲の指定も必要となるだろう。

**Comment by monomonosu** [comment]
あ、確かにそうだな。
そこまでいくとなると、ページを遷移させる方式の方が良さそうな気がしてくる。
日付範囲指定の必要性はいまいちピンと来ていないんだけど、選択した請求書の日付を項目ごとに表示するだけじゃダメなのかな？

**Comment by gamasenninn** [comment]
たしかに、処理内容がまったく異なるので、別ページをつくったほうがよいだろうね。
日付指定の必要性は、かならずしも、月初めからじゃないし、締め日も各社違うから、年月日～年月日という範囲で指定できないとまずくないか？

**Comment by gamasenninn** [comment]
簡単でいいので、一括請求画面のポンチ絵描いてみないか？

**Comment by monomonosu** [comment]
とりあえず図に書いたようなボタンを押下すると機能が使えるような感じにする。

![image](https://user-images.githubusercontent.com/77572073/177677458-62b5bb7e-d2bf-486e-ada7-c739a807f290.png)

**Comment by monomonosu** [comment]
「請求書一覧」を押下するとフィルタリング込みの請求書一覧を全て出力できるようにする。

出力するもののレイアウトは後でイメージを送る。

**Comment by monomonosu** [comment]
合計請求書はモダールを出現させ、得意先をセレクトボックスで選択するとそれに紐づいた請求書を表示。
チェックボックスを選択したものをまとめて出力できるようにする。

**Comment by gamasenninn** [comment]
『合計請求書』ボタンを押して表示される合計請求の画面はこれでよいと思う。だが『請求書一覧』ボタン押下での一括請求書出力は蛇足ではないかと思う。なにをしたいのかよくわからない。
