### ISSUE TITLE
グラフページの作成

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1104]
請求書の合計金額をグラフ化して見える化するページを作成する。

- グラフ化対象：月の合計請求金額
- グラフ形式：棒グラフ
- グラフページは「チェック」ページから飛べる形にする。

以上の条件でざっくりとした感じでページを作成して、そこからデザイン等のブラッシュアップをしていく。

**Comment by gamasenninn** [comment]
ライブラリの選定含めて、よろしく

chart.jsは使いやすかった。
https://github.com/gamasenninn/chart-sample/tree/main/chartjs

**Comment by monomonosu** [comment]
俺もグラフ作成ライブラリではchart.jsがダントツでモダンっぽいUIだと感じたのでこれで行こうと思う。
