### ISSUE TITLE
自動ログアウトが若干早いらしい

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1160]
３０分なにも操作しない場合、自動ログアウトを設けているが、これが若干早いらしい。
まずは状況の確認から。

**Comment by monomonosu** [comment]
@gamasenninn 
検証してみたが、早くなってしまうという実感はなかった。
これってもしかしてクリックイベント時にもライフタイムを延ばすって事かもな。
現状ではセッションライフタイムを延長するのってAPIが呼ばれたときのみだよね？

**Comment by monomonosu** [comment]
@gamasenninn 
空クリック時にもセッションライフタイムを更新して欲しいとの事なので、jsonのみ返すAPIとかを適当に作成して、クリックイベントで呼び出してみる。

**Comment by gamasenninn** [comment]
なるほどそういうことだったのだな。
