### ISSUE TITLE
得意先の更新画面で請求書一覧を観覧できるようにする

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1163]
得意先の更新画面で、その得意先に紐づく請求書を一覧で表示されるようにする。
なので、得意先更新画面の左半分は得意先情報を入力するためのフォームを縦長で全表示。
右半分は請求書一覧を表示させる感じにする。

**Comment by gamasenninn** [comment]
新規に一覧機能を作るのではなく。既存の一覧を<iframe>などで呼び出す形にしたほうがよい。

**Comment by monomonosu** [comment]
@gamasenninn 
なるほど、その線で調べてみる。
