### ISSUE TITLE
マルチウィンドウを開くたび、右にズレていく

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1196]
マルチウィンドウモード時に、ウィンドウを開く→閉じる→開く→閉じると繰り返すとウィンドウがだんだん右に寄ってきてしまうので修正する。
（ライブラリの仕様？）

![goto-right](https://user-images.githubusercontent.com/77572073/172765703-41d55099-4995-45e6-bded-d23b15ab12fb.gif)

**Comment by gamasenninn** [comment]
これはバグじゃないよ。次に開くウィンドウの位置をずらさないと同じ位置に被ってしまうため。

**Comment by crescom-ohira** [comment]
だとすると最初に出てくるウィンドウの位置を右寄りから出てくるようにすることはできますか？
![【修正】マルチウィンドウの位置](https://user-images.githubusercontent.com/97567597/174278982-b7230daa-2bdf-40a8-a282-ca13936aec77.png)
