### ISSUE TITLE
seeder_init.pyを使わない方法を模索したほうが良い

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1241]
セキュリティ的にまずいので、seeder.init.pyを使わない方法を模索した方が良さそう。

**Comment by gamasenninn** [comment]
パスワード部分は.envから読んでくるようにしたほうがよいかもね。

**Comment by monomonosu** [comment]
そのほうが良いかもしれないな。
ちょっと調べてみる。

**Comment by monomonosu** [comment]
.envを使うとエンジニア以外はセットアップのハードルが高くなるので初めにadmin権限を用意。
セットアップ完了後にユーザーを登録して、初めに用意したadmin権限を削除するような感じにして欲しいとの事。

**Comment by gamasenninn** [comment]
プライベートリポでも問題ないと思う。

**Comment by monomonosu** [comment]
それで行こうか
