### ISSUE TITLE
請求書編集時に未保存アラートが表示されない事があるらしい。

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1282]
例の如くまずは現象の再現から

**Comment by gamasenninn** [comment]
明細行だけ変更すると未保存アラートが表示されないようだ。

**Comment by monomonosu** [comment]
なるほど、何となく思い出してきた。
多分明細行の途中挿入のタスクで修正したところが悪さしてる気がする。

**Comment by gamasenninn** [comment]
テストプログラム書いて現象確認できた。

https://user-images.githubusercontent.com/61409504/178403901-8cf06738-621e-4d71-a6a0-88271c8d3a65.mp4

**Comment by gamasenninn** [comment]
![update alert test -- update invoice alert test (failed)](https://user-images.githubusercontent.com/61409504/178404008-9cd6ae57-295b-45d3-ac82-99950586a71b.png)
