### ISSUE TITLE
合計請求モーダルの客先セレクトボックスの廃止

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1295]
合計請求モーダルの請求一覧を出す前にセレクトボックスで得意先を選択するが、これを入力→検索方式にして欲しいとの事。
若干矛盾が発生しそうだが、とりあえずやってみる。

![image](https://user-images.githubusercontent.com/77572073/178881911-70cf1704-fec0-457b-a194-d08d3ac4f7e6.png)

**Comment by gamasenninn** [comment]
「株式会社」とかのキーワードで検索すると複数の得意先読んできてしまうので、矛盾が発生するわけで。その場合に「印刷」処理を実行しようとしたとき「複数の得意先が選択されています。一社に絞ってください」とかのアラートかけないとだめだよね。複数の得意先も同時に処理して、という仕様は必要条件ではないし、MVPではないし、プログラムが複雑で重くなり、なおかつユーザの理解を超えてしまう可能性あるので、なしね。

**Comment by monomonosu** [comment]
別の得意先を選択できる状態で大丈夫との事。

**Comment by gamasenninn** [comment]
最終的には一件の得意先にしぼり込めたら「印刷」が可能ということにしたい。意義がある場合は仕様とその理由をISSUEにあげてほしい。議論しよう。

**Comment by monomonosu** [comment]
とりあえず検索欄入力での検索機能に切り替えた。
これでフロント側は大体完成したかも。
もし必要な値などがあれば言ってくだちい！
