### ISSUE TITLE
rcloneを使用して定期的にDBのバックアップを取る。

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1299]
VPSに構築したsoho-caddieのDBバックアップ自動化のためにパイプを作った方が良さげ。

**Comment by gamasenninn** [comment]
なんのパイプ？
どういった仕組みを考えてる？

**Comment by monomonosu** [comment]
この前言っていたバックアップ用のライブラリ？でだね。
すまんのだが名前を忘れてしまった。なんだったっけ。

**Comment by gamasenninn** [comment]
rclone。これはライブラリというより実行形式のコマンドだね。
[rclone](https://rclone.org/)
マルチプラットフォームなので、ポータビリティがとてもよい。windowsでもlinuxでも動くというのがポイント高い。

**Comment by monomonosu** [comment]
rcloneか。これの使用を検討しよう。
もう一つの手段として、gitを使ってgithubのプライベートリポジトリにpushしちゃうのもありかな？と思ったんだけどどうだろうか。

**Comment by gamasenninn** [comment]
リポジトリにバイナリとかデータ本体を置くのはgithubルールの原則から逸脱しているので、それは悪手。

**Comment by monomonosu** [comment]
なるほど、確かに。
ではrcloneを使用してみます！

**Comment by gamasenninn** [comment]
SFTP、WEBDAV、その他rcloneが対応しているコピーサービスなどが使用できるサーバ、クラウドならどこでもコピーできるよ。

**Comment by monomonosu** [comment]
@gamasenninn 
バックアップを取るPC側でrcloneのインストール・初期設定が必要になってくるが、
https://github.com/Crescom-SohoCaddie/buckup-shell
にバックアップ自動化用シェルスクリプトを作成してみた。
