### ISSUE TITLE
(feedback)請求書・見積書のインポート周りがわかりづらい

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1315]
- [x] ファイルのドロップ（アップロード）を促す文言を「請求書の内容の写真やメモを貼り付けて下さい。」的な文言にする。
- [x] ファイルの削除ボタンはアイコンだけだとわかりづらいとの事なので、例えばポッパーを表示して、「選択ファイル削除」とかに変更してみる？
- [x] アップロードファイルの表示切替ボタン・削除ボタンがどの要素に属しているかわかりづらいとの事なので、例えば要素を囲うdiv要素の背景を薄い色で囲ってあげるとわかりやすい？

![SHOH CADDIE1](https://user-images.githubusercontent.com/77572073/179878328-37c3b2c2-93dc-4c7d-9d88-791729461fa0.png)

**Comment by gamasenninn** [comment]
「請求書の内容の写真やメモを貼り付けて下さい。」となると請求書のそれ!に限定されてしまうので、逆に混乱を招くんじゃないか。
たとえば「画像やメモを貼り付けて」くださいとかの、やや抽象化した言い回しのほうがよいような気がするのだが。

**Comment by gamasenninn** [comment]
＞アップロードファイルの表示切替ボタン・削除ボタンがどの要素に属しているかわかりづらいとの事

細い線などで囲めば要素はわかりやすくなるかも。もちろん薄い色でもいいかも。まあ、実験してみるといいだろう。

**Comment by gamasenninn** [comment]
あと削除ボタンとかリストボタンなんだが、アップロードボックスの下あたりに配置すれば、なにをするものか明確になると思うのだが。まあ、それはデザイン的なものなので、あくまで提案ね。画面仕様決定者にお任せする。

**Comment by monomonosu** [comment]
>「請求書の内容の写真やメモを貼り付けて下さい。」となると請求書のそれ!に限定されてしまうので、逆に混乱を招くんじゃないか。
たとえば「画像やメモを貼り付けて」くださいとかの、やや抽象化した言い回しのほうがよいような気がするのだが。

PDF等のファイルが含まれるかわかりずらいので、それは確かにそうかも。
