### ISSUE TITLE
合計請求モーダルの検索欄にオートコンプリート機能を追加。

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1320]
合計請求モーダルの検索欄にオートコンプリート機能を追加する。
見積の編集画面等で使用しているdatelistを使うと良いかもしれない。

**Comment by gamasenninn** [comment]
いい考え。datalistの場合、明確にDBにあるデータを拾ってくるから、混乱を避けられるし、顧客を一意に限定できるというメリットがあるね。
