### ISSUE TITLE
invoice->customerのリレーションを張る

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1336]
合計請求機能の実装（バック） #1277

の実装でinvoice->customerのリレーションが必要みたいなので、リレーションを張る。

**Comment by gamasenninn** [comment]
・別のスキーマを用意する
・customerが必要なときはAPIのパラメータで指定する
的なところでよいだろうか？

**Comment by monomonosu** [comment]
パラメータで振り分けできるかどうかも見てみる。

**Comment by monomonosu** [comment]
パラメータで振り分ける場合、別のスキーマが必要になってくる。が正しいか。
