### ISSUE TITLE
軽減税率機能の実装

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#1350]
軽減税率機能を実装する。
そこで問題になってくるのが税金計算だが、これは明細ひとつひとつに10%or8%をかけるのではなく、10%のものと8%のもの２種類に分けて集計をし、その後に課税をしていく方式をとる。
（例）鉛筆（１５本）：４５０円×１０％　＝　４９５円
　　　（ハム太郎（１匹）：１０００円　＋　ハム次郎（２匹）：２０００円）×　８％
　　　＝３０００円　＋　２４０円　→　画面への出力に使用。
　　　＝３２４０円　→　計算に使用

　　　総計：３７３５円

という感じ。

印刷側は、軽減税率対象のものに※等を付与して欲しいとの事。（写真２参照）

![image](https://user-images.githubusercontent.com/77572073/181694769-a97613a3-aa6c-44f0-afbd-09d23464e7a7.png)

![image](https://user-images.githubusercontent.com/77572073/181696484-b0448426-7bcd-474a-ae1b-3c750e79ecd2.png)

**Comment by gamasenninn** [comment]
適格請求書の場合は、消費税欄が８％と１０％と2つに分かれて表示させ、それを集計して消費税の合計とする、というものではなかったっけ？

**Comment by gamasenninn** [comment]
それと今のCaddieの明細行入力では消費税項目がないからカラムの追加が必要ではないかな。

**Comment by monomonosu** [comment]
前者の方は、それを正とするとフロント側でのデータの整形・出力する請求書のレイアウト等の変更が必要になってきそうだね。

**Comment by monomonosu** [comment]
後者の方は、確かにそれは必須になってくるよね。前提としてSettingにreducedTaxカラムは確実に追加するとして、パッと思いついた案で行くと、
①Invoice_ItemにisReducedTaxカラムを追加して、それを元に、isReducedTax=trueのものにはSetting.reducedTaxを掛けるようにする。
②Invoice_ItemにもReducedTaxカラムを追加してしまい、明細登録時にチェックボックスにチェックが付いたものはSetting.reducedTaxから引っ張ってきた値を直接Insert。カラムに直接入っているInvoice_Item.reducedTaxを元に計算を行う。

って感じのこの２案になるかな？

**Comment by monomonosu** [comment]
どちらかと言うと②案の方が柔軟性はあると考えていて、たとえば今後軽減税率が変更されるとなった時に過去の軽減税率は８％。現在の軽減税率は〇％として継続的に安定するのではないかと考えている。

**Comment by gamasenninn** [comment]
たしかに②のほうが変更強度が高い。
軽減税率8%というのは政治の歴史からすれば真夏の逃げ水のように一瞬の出来事に違いない。

ところで適格請求書については政府が発行する下記のPDFの７ページ目に詳しい。
条件が列挙されているので参考にされたし。
[適格請求書等保存方式の概要](https://www.nta.go.jp/taxes/shiraberu/zeimokubetsu/shohi/keigenzeiritsu/pdf/0020006-027.pdf)

**Comment by gamasenninn** [comment]
あ、それと商品マスターにも軽減税率カラムが必要そうだね。明細行に商品選んだとき人力判断になり、isReducedTaxチェックを忘れてしまうかもしれない。

**Comment by monomonosu** [comment]
とりあえずフロント側は完了した。
