### ISSUE TITLE
合計請求レイアウト決定

### ISSUE THREAD

**Issue by gamasenninn** [Crescom-SohoCaddie/soho-caddie#1354]
合計請求のロジックが完成したので、
合計請求書のレイアウトをください。
イメージもあると助かります。

**Comment by monomonosu** [comment]
@gamasenninn 
>後で送ります。

との事。少々お待ちを！

**Comment by gamasenninn** [comment]
了解

**Comment by monomonosu** [comment]
合計請求のファイルはslackで送付したファイルの参照をお願いします。

合計請求書はほぼ必ずと言っていいほど2ページ分必要になってくるので、
１ページ目は下記の画像のように、

![image](https://user-images.githubusercontent.com/77572073/182278929-136beeab-7b42-463f-b1a7-9d1d2901ca94.png)

データが長くなり、２ページ目までいった場合、２ページ目は下記のようにする。

![image](https://user-images.githubusercontent.com/77572073/182279134-fb2bfa14-4686-4107-8d3c-4ae6ea2d7d4d.png)

**Comment by monomonosu** [comment]
ここで一つ疑問点。
複数の請求書を合計すると件名どうするか問題が出てくる。

**Comment by gamasenninn** [comment]
それと、同じ文脈で、請求書Noどうするか問題もね。

**Comment by monomonosu** [comment]
請求・見積書カスタム用の合計請求書レイアウト変更は今のところ必要無いとの事。

**Comment by monomonosu** [comment]
件名は入力モーダル等を出して、入力を促す。

**Comment by monomonosu** [comment]
請求書Noも任意で入力するようにする。
自動で番号の生成は必要ないとの事。

**Comment by monomonosu** [comment]
まとめると、請求書選択→印刷　の間に件名と請求書Noを入力するためのモーダルを追加するという感じ

**Comment by gamasenninn** [comment]
了解。UIができたらPDFに実装します。

**Comment by gamasenninn** [comment]
ちょっと心配なのだが、合計請求書における件名と請求書Noはあくまでそのときだけの入力なので、DBには保存されないわけだよね。あとで請求番号を照会したい場合はどうするのかな？

**Comment by monomonosu** [comment]
合計請求書は保存する方向で進めるとの事。

**Comment by gamasenninn** [comment]
了解。

**Comment by monomonosu** [comment]
@gamasenninn 
合計請求書No.＆合計請求書の件名をＤＢに保存できるようにしている。
PDF生成ロジックにデータを渡す必要があるわけだけども、件名はモーダルで入力を促しているから問題ないとして、合計請求No.に関しては一度バック側で処理する必要があるから、合計請求書作成→ＤＢ保存(合計請求No.作成)→フロント側でPDF生成用データ整形→PDF生成って手順になってしまう？
だとすると合計請求No.の生成ロジックを見直す必要がでてくる可能性あり。
もし合計請求書発行時のデータ整形で問題が出たら言ってください。

**Comment by gamasenninn** [comment]
これ、たしかに問題なんよね。DBに保存してからでないと請求番号が得られないから。
ＤＢ保存(合計請求No.作成)->(請求番号)->PDF生成
という手順にするしかないのは確かだな。

**Comment by monomonosu** [comment]
DB保存(TotalInvoice)→請求番号取得→PDF生成となると、PDF生成時に帰ってくるレスポンスであるPDFファイル名が取得できないという問題が発生したので、DB保存(TotalInvoice)→請求番号取得→PDF生成→DB更新(TotalInvoice.fileName)とする事にした。
