### ISSUE TITLE
フロント側でバリデーションをちゃんと設ける

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#163]
DBの型と違うものが入力されてしまうとシステムが落ちてしまうので、後でフロント側でバリデーションを設ける。

**Comment by gamasenninn** [comment]
とりあえず<b-form-input.........> でtype='number'としておこう。数値項目しか入力できなくなるから。

**Comment by monomonosu** [comment]
毎回対応しているので、Closeとしてしまう。
