### ISSUE TITLE
商品入力時、カテゴリー、単位、メーカー選択での直接入力でDB自動登録を可能とする。

### ISSUE THREAD

**Issue by gamasenninn** [Crescom-SohoCaddie/soho-caddie#484]
直接入力をした場合、DBに登録するかどうかを聞き、【はい】なら登録、【いいえ】なら登録しない。
当然、メーカーなどのデータは完全ではないので、あとで補完する。

**Comment by monomonosu** [comment]
これは是非そうして欲しいとの事なので実装する。

**Comment by monomonosu** [comment]
これはdatalistで似たような実装済みなので、このままCloseとする。

![image](https://user-images.githubusercontent.com/77572073/165196735-8cdbbb88-fca7-4af6-9792-b153008aea52.png)
