### ISSUE TITLE
ユーザー登録には任意番号を振る

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#745]
ユーザー一覧でクレスコム権限は隠すようにした #741
でcrescom_support権限のユーザーを一覧に表示させないようにしたが、IDが歯抜けに見えるのが嫌みたいなのでユーザー登録時に任意番号を登録できるようにとの事。
任意番号は重複禁止。空文字の禁止。
一覧で表示する際はIDを非表示にして、任意番号を表示する。

**Comment by gamasenninn** [comment]
IDを非表示にするだけでいいのではないか？任意番号の役割が不明。重複禁止はログインIDだけでよいと思う。ちなみに、現時点ではname項目をログインIDにしてる。

**Comment by monomonosu** [comment]
うん、それだけでいいと思うのでこれも提案してみる。

**Comment by monomonosu** [comment]
uniqu属性付与、なかなか苦戦しているのでnameを重複禁止にするのもどうやれば良いかわからんが

**Comment by gamasenninn** [comment]
任意番号のunique付与実験はうまくいった？
migration時問題あり？

**Comment by monomonosu** [comment]
なかなかうまくいかず、苦戦している。
そう、やはりmigrationで詰まってしまう

**Comment by gamasenninn** [comment]
重複禁止migrationに関してはタスク消化が落ち着いたら検証しよう。

**Comment by monomonosu** [comment]
そうしよう
