### ISSUE TITLE
ログイン履歴機能の実装

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#777]
ログイン履歴を参照できる機能を付ける。
ログインの履歴を保存しておくためのテーブルが必要になるかも？

![image](https://user-images.githubusercontent.com/77572073/158008715-08fc3f23-4698-49ac-82cd-0dc961da4e8d.png)

**Comment by gamasenninn** [comment]
このへんはVIPの原則から言ってなくても困らないものだから、次のリリースのほうがよいと思う。

**Comment by monomonosu** [comment]
利用者寄りというよりも開発寄りの機能だしな、相談してみる

**Comment by gamasenninn** [comment]
DBは作っておいていいと思うが、UIを作るとなると、それなりの期間と調整が必要になるので、少なくてもUIは次のフェーズでということで。

**Comment by monomonosu** [comment]
なるほど、とりあえずでテーブル作ってプールさせとけばデータ参照はできるな。

**Comment by gamasenninn** [comment]
うむ。もしやるならその程度で抑えておいたほうがよい。

**Comment by gamasenninn** [comment]
もし、テーブルをつくるなら、ログイン履歴というより、操作履歴にする。そうすればログインだけでなく、各種操作の履歴がとれる。ログイン、追加、更新、削除、ログアウトなど、さまざまな履歴が取れる。プログラム的にはログのデコレータを作っておけばよいだけなので、APIだけに実装するだけですむ。そうすることで後々の対処はそんなに大変ではない。

**Comment by monomonosu** [comment]
操作する度にログテーブルにINSERTするだけで良いもんな

**Comment by monomonosu** [comment]
バック側の実装が完了したが、フロントのページは作らない旨を大平さんに伝える。

**Comment by monomonosu** [comment]
フロントページの作成はとりあえず次フェーズでもOKとなったが、次フェーズの最優先で作成して欲しいとの事。
DBの更新ログは今の段階で全て取ってほしいとの事なので、全部取るようにする。

**Comment by gamasenninn** [comment]
了解。
デコレータ使ってほしい。ソースがログイン機能で埋め尽くされることがないので。

**Comment by gamasenninn** [comment]
フロントページの件なんだが、モーダルで簡易的に100件分ぐらい表示するぐらいなら、今回のフェーズでも間に合うかもな。

**Comment by monomonosu** [comment]
バック側が完了したので一旦Close。
フロント側の実装を次フェーズで行うので、IssueをWikiに残す。
