### ISSUE TITLE
合計欄のレイアウトのズレ問題についての考察と解決のための実験。

### ISSUE THREAD

**Issue by gamasenninn** [Crescom-SohoCaddie/soho-caddie#792]
請求明細の金額欄と合計欄においてレイアウトのズレが発生する。なぜなら、それら二つのブロックは構造上別ものであり、ブラウザの伸縮によってレイアウトのズレが発生するのは自明である。構造上別物であるがゆえに、この方式ではどんな優れた技術をもってしてもズレの問題は解決できない。

このズレを解決するにはブロックを同一のレイアウト上に配置しなければならない。その術式としては、ｂテーブルのフッターにテーブル要素を追加し、金額欄と同じデータブロックに合計欄を配置すること。これによって構造上同一化するのでズレの発生は解決する。
しかし、ここで大きな問題が残る。備考欄は金額欄の横に配置されるため、ブラウザを縮ませたときに、備考欄と合計欄はレシポンシブにならず、回り込みができなくなる。ズレの問題でレスポンシブを犠牲にすることは、本末転倒である。たとえていえば、車のワイパーの位置が気に入らないので車体を交換しエンジンの位置まで変えるようなものである。

さて、この二つの矛盾する問題を解決するためにはどうしたらよいか？考え得る現実解としては、フッターテーブルに配置するのはSPANで結合され一つのデータブロックとなったところに備考欄と合計欄を同居させることである。備考欄は左よせ、合計欄は右よせとしてcolと使用して配置する。
回り込みが発生すると、当然備考欄が上になるが、これを合計欄が上になるように設定する。こうすることでレシポンシブに対応することができるのではないかと考察する。＋ボタンは合計欄のデータブロックの横に配置することで、合計欄と＋ボタンは回り込みが発生しないとものと推測する。

以上、この術式を実験して可能性を探るものとする。

当ISSUE、関係者回覧要確認。

**Comment by monomonosu** [comment]
うーむ、他にもやらなければならない事が沢山あるのでこれは次フェーズに実験する方向の方が良いと思うな。
ズレを修正するためだけに、相当な力技を使わないといけなくなるので負債になるのではないかと思う。
時間的な問題と、早い段階から負債を残すのはどうかと俺は思う。
