### ISSUE TITLE
Itemsの商品コード(itemCode)はUNIQUEにする

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#873]
商品の商品コードは他と被らないようにUNIQUEにして欲しいとの事。

（個人的には同じ商品を登録しておいて商品名の表示を変えたい、同じ商品でも価格を状況によって変えたいなどの需要もあると思うからUNIQUEにしない方が良いんじゃね？と思っている。）

**Comment by gamasenninn** [comment]
商品コードがskuならユニーク推奨だが、そうではないならこの限りではない。でも今回は商品コードをアップロードフォルダー名にしちゃってるんだよね。そういう意味ではユニークのほうがいいが、後ろ向きの理由くさいね。

**Comment by gamasenninn** [comment]
まあ、アップロードIDは商品のプライマリキー（商品ID）にすれば問題ないので、結局は、商品コードはSKU扱いか、そうじゃないかの違いを明確にすればよいだけだね。
もし、UNIQUE属性をつけるとなると、商品入力時、商品コードは必須になる。空欄も一つしか存在させられないので、未入力は許されなくなる。ユーザはそれがストレスにならないだろうか？

**Comment by gamasenninn** [comment]
空欄が多数発生してもよい。だが、入力される値は必ずユニーク。という仕様にしたい場合は、DBはユニーク属性を持たせないで、フロント側のバリデーションで対応する、という術式もあり。

**Comment by monomonosu** [comment]
なるほど、その方式で行った方が良さそうだな。
とりあえずフロント側でバリデーションをかける方向で進めるか。

**Comment by gamasenninn** [comment]
ちなみにここでいう空欄はあくまで実体のある空欄のことね。Unique制約の場合、NULL値は複数あっても許される。なので、insert時に当該カラムをいじらなければ登録は可能。そういう意味ではUnique制約をつけてもいいのだが、わざと商品コードを重複させたい場合は、その限りではない。そういう要望も出てくるかもしれない。いまの時点ではフロント側バリデーションで対応しておいたほうが2つの矛盾する要望を立たせる意味で無難だな。

**Comment by gamasenninn** [comment]
仕様が明確に固まった時点でモデル・APIに重複エラー入れるかどうか決定しよう。いまはフロント側バリデーションで対応しよう。

**Comment by monomonosu** [comment]
了解した。
