### ISSUE TITLE
請求書控え印刷機能

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#913]
請求書の控えを印刷できる機能を追加する。
控え請求書はモノクロで出力。ヘッダーに「（控え）」を追加する。
そして、その印刷ボタンは印刷ドロップアップボタンの項目に追加する。

![image](https://user-images.githubusercontent.com/77572073/160039568-8bafef4d-978f-4ff8-bb40-1c08ad9ce642.png)

![image](https://user-images.githubusercontent.com/77572073/160038121-301355eb-2f6d-45da-9933-abe4046a1c30.png)

**Comment by monomonosu** [comment]
ちなみにこれは請求書のみの機能。

**Comment by gamasenninn** [comment]
モノクロ出力は結構工数かかるな。
方法は2つ
①ちょっと思いつくのがgostscript使う。だが、外部プロセス起動になるし、それ自体が重いので、あまりよい手とはいえない。
②画像だけPillowでグレースケール化すればモノクロな雰囲気が出せるが、透過gifの場合は、うまく変換できないかもしれない。それと、レイアウト定義スクリプトの大幅な改造が必要になる。

**Comment by gamasenninn** [comment]
グレースケール化の実験としてghostscriptで変換してみた。かなりの精度で変換が可能。windows環境では変換時に窓が一瞬出るので気になる。結論としては使えそう。歴史もある。ユーザも多い。
だが、問題はライセンスがAGPL。よってすべてのソースコードは公開。という前提がある。ネットのサービスの場合でもソースコードは公開しなければならない。
それでよいなら、ghostscript使うが、どうだろう？

**Comment by gamasenninn** [comment]
大平さんと話をして、今回はグレースケールは見送り。ユーザが印刷時に白黒を選択するという仕様になった。

**Comment by monomonosu** [comment]
ボタンをまだ作成してないので、まだCloseしなくて良いよ。
追加したら閉じておく。ボタン追加やっちゃうね
