### ISSUE TITLE
粗利金額の表示機能

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#915]
請求・見積の新規・更新画面の明細欄に粗利を表示する機能を設ける。
表示項目は「原価」「原価単価」「原価率」「粗利金額」の４つ。
原価＝商品の個数によって変動。　原価単価×個数
原価単価＝現状「原価」で表示しているもの。
原価率＝現状あるもの。変更なし。
粗利金額＝商品の個数によって変動。（値段×個数）ー（原価単価×個数）

![image](https://user-images.githubusercontent.com/77572073/160039873-aa740f30-826d-4474-af8c-a09ad11098ed.png)

**Comment by gamasenninn** [comment]
粗利がわかるっていいね。
