### ISSUE TITLE
CDNを使用している箇所があるので、ローカルにDL

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#919]
所々ライブラリをCDNで利用している箇所があるので、ローカルに置くようにする。

- [x] invoice_dust.html
- [x] invoice.html
- [x] item.html
- [x] mw.html
- [x] quotation_dust.html
- [x] quotation.html

**Comment by gamasenninn** [comment]
mw2.htmlは使ってないな。なので、あとで消しておく。leaflet.htmlは将来使う予定なのでこのまま残そう。
そういえば、他のファイルで使っていないものが多々あるので、この機会にお掃除しておくか。ISSUE上げる。

**Comment by monomonosu** [comment]
了解した。mw2とleafletをリストから外した。
