### ISSUE TITLE
請求・見積・商品一覧のアップロード数はクリップマークに変更。

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#924]
請求・見積・商品一覧画面でファイルのアップロード数を右端に表示しているが、これをクリップマークに変更する。
ファイル件数に関わらず、アップロードがあればクリップを表示するのみで良いとの事。
使用するアイコンは社内PＣ内にあるので、後日実装。

- [x] クリップマークへ変更
- [x] ディレクトリ直接走査方式に変更（DB処理しない）

![image](https://user-images.githubusercontent.com/77572073/160232553-454587c1-c1c2-4948-be0f-a524e99bed1b.png)

**Comment by gamasenninn** [comment]
これ、未保存警告の件とからめて、添付ファイルあるなしはDB管理じゃなくしたほうがいいかな。getInvoice()するタイミングでディレクトリを読みにいってフラグをマージするほうが自然のような気がしてきた。それをやれば、未保存警告のバグ的な仕様問題ものはなくなるよね。

**Comment by monomonosu** [comment]
なるほど、若干処理は多くなるが自然かもしれないな。

**Comment by gamasenninn** [comment]
ファイルあるなしのロジックはワシが入れるので、クリップマークへの変更はやってしまっていいよ。

**Comment by monomonosu** [comment]
了解した。プルリク出すね。
