### ISSUE TITLE
ユーザごとの個別カスタマイズ対応について

### ISSUE THREAD

**Issue by gamasenninn** [Crescom-SohoCaddie/soho-caddie#932]
・複数ユーザからの要望があがってきた。とくにPDF出力については１００％といっていいほど個別のカスタマイズが必要になる。個別のファイルをどのように扱うかの戦略をたてる必要がある。

- 個別カスタマイズ対応のディレクトリを用意。もしファイルがあったらそれを優先とする。mixinで対応できるだろうか・・・・
- 個別カスタマイズごとにリポジトリを分け、ゴリゴリとファイルをいじっていく。・・・かなりカオスになりそう。
- その他、考えられることを提案してほしい

**Comment by monomonosu** [comment]
どちらもメリットデメリット出てくるよなぁ...
前者は共通化できる所は共通化できるが、干渉が大きくなるよなぁ...
後者は干渉はなくなるが、ユーザーごとに環境が枝分けれして管理は大変そうだし。

この機能は全ユーザー使いそうだなって機能は中枢のcaddieに反映しちゃった方が良いかもだが、限界あるよな...

**Comment by monomonosu** [comment]
金銭の発生しない機能追加は中枢にマージ。
金銭の発生した機能追加は個別リポジトリにマージ。というルールを設ける？

**Comment by gamasenninn** [comment]
なるほど。金銭の発生するものは、最も重要なカスタマイズになるから、個別リポは基本だな。
ただ、金銭の発生するものでも、入金処理などをあとから追加したい場合は、オリジナルに取り込みたいよね。

**Comment by gamasenninn** [comment]
PDFのフォーマットの変更は中枢機能の一部にしたほうがよいかなと思っている。なぜなら、フォーマットを変える程度で個別リポを作るのはかなり手間になりコスパが悪い。しかもユーザが頻繁にアップデートしたいものだと思える。
以上のことから、PDF出力フォーマット変更は、システムで柔軟に対応したい。その方法としてはカスタムディレクトリを作成し、もし、そこにファイルがあったら、そのスクリプトを優先するようなイメージかな。
動的なスクリプト読み込みをすればそれが可能なような気がするので実験してみる。
