### ISSUE TITLE
ユーザーのパスワード表示・非表示画面は暗号化したもので良いのか否か。

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#942]
もし暗号化したものではなく、平文で表示して欲しいとの事であれば修正する。

**Comment by gamasenninn** [comment]
セキュリティを考慮すると、平文はまずいと思う。このシステムを知っている人間ならDBから平文抜いてしまえばよいわけで。

**Comment by gamasenninn** [comment]
最初は平文で登録できるが、パスワード変更すると暗号保存になるのが今の実装。

**Comment by gamasenninn** [comment]
平文管理はブラウザに任せるのが、今のトレンドだよね。

**Comment by monomonosu** [comment]
ユーザーの一覧表示時には●●表示を暗号化したものの8文字表示まで、
更新画面に行って、目のマークを押下したら暗号→複合したものを表示して欲しいとの事なのだが、これはまずい？

**Comment by monomonosu** [comment]
DBには暗号化されたものが入っているが、更新画面でパスワード参照時に目のマークが押された時にそれに対して複合フィルター的な処理をするって感じだな

**Comment by gamasenninn** [comment]
SHA-256によるハッシュは複合できないよ。不可逆性が成り立つから暗号は成立する。

**Comment by gamasenninn** [comment]
ちなみに目のマークを押して平文がでてくるのは、ブラウザの世界だけ。

**Comment by monomonosu** [comment]
復号はしなくてOKとの事。
目のマークで文字を表示する機能を廃止。
●●で表示するパスワード数を８桁までにする。
という方向になった。

**Comment by gamasenninn** [comment]
了解。ISSUEはクローズしてくれ
