### ISSUE TITLE
得意先に任意番号を付ける

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#947]
得意先に任意番号カラムを追加。
属性はUNIQUE。（重複なし、空欄なし）
これは、未入金分の管理等に使用するとの事。(FK)
桁数は5桁くらいを想定して欲しいとの事。

**Comment by gamasenninn** [comment]
この任意番号は何とリンクするの？

**Comment by monomonosu** [comment]
未入金チェックの実装 #950

で未入金の請求一覧を表示する時にこの任意番号でソートして欲しいとの事。

**Comment by monomonosu** [comment]
- [ ] カラムの追加
 - [ ] フロント側の入力欄作成
 - [ ] 得意先の新規作成・更新時に任意番号の入力がなければエラーモーダルを出すようにする。
