### ISSUE TITLE
チェックページの作成

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#948]
各種リンクボタンにチェックページへのリンクボタンを追加する。
このチェックページは、「未入金チェック」や「未請求チェック」等を行えるページへのポータルとなるようにする。

![image](https://user-images.githubusercontent.com/77572073/160959669-20d89497-c7a6-41be-a9fb-7da60a693dd6.png)

**Comment by gamasenninn** [comment]
このUIだとこのぶん画面が必要っぽいのだが、giuhubのISSUE管理のようにフィルターレベルでチェックできたほうがいいのではないか？あるいは、チェックボックス風とか、ドロップダウンにして、チェック一覧はあくまで一画面にしたほうがいいと思う。

**Comment by gamasenninn** [comment]
あ、でも未入金チェックと未請求チェックは性質の違うロジックになるかもしれないし、今後増えるであろうチェック処理もそれぞれ特殊性もっているだろうから、単純に一般化はできないかもな。だとすると、このUIでいいかもしれない。もし、一般化できるようなら、あとで統合するということでもよいな。

**Comment by monomonosu** [comment]
issue管理のページ無くなっててイメージがつかめない...

**Comment by gamasenninn** [comment]
ページのやつじゃなくて、いつも使っているgithubの機能のISSUE管理
https://github.com/Crescom-SohoCaddie/soho-caddie/issues

**Comment by monomonosu** [comment]
未入金チェックを選択すると、こんな感じで請求書ページとほぼ同じ一覧画面として出して欲しいとの事なので、親父が考えてる方式とほぼ一緒かな？

![image](https://user-images.githubusercontent.com/77572073/160974139-8ff17505-f448-4e64-9439-30e086658f96.png)

**Comment by monomonosu** [comment]
なるほど、「○○チェック」分ページを作るとその分、一個修正しただけで他のページ分修正を加えないといけないのか...
確かに共通化（チェックボックスでフィルターをかける等）した方が良い感じあるな。

**Comment by monomonosu** [comment]
> あ、でも未入金チェックと未請求チェックは性質の違うロジックになるかもしれないし、今後増えるであろうチェック処理もそれぞれ特殊性もっているだろうから、単純に一般化はできないかもな。だとすると、このUIでいいかもしれない。もし、一般化できるようなら、あとで統合するということでもよいな。

ただ、これも確かにその通りだしな...
途中で方向転換する感じで良いのかもしれないな。
