### ISSUE TITLE
入金処理の実装

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#952]
請求書の更新画面に入金処理を実装する。

- [x] １枚目の画像のようにボタンを追加（請求・未入金共通）
- [x] 入金処理は請求書１枚に対して行う。請求Noで管理する。（請求Noで管理せずともforeignkeyでリレーションしてるのでそこは心配する必要ない？）
- [x] ２枚目の画像のような~~ウィンドウ~~モーダルを作成。
- [x] ↑このウィンドウのタイトルバーには請求No.を表示する。
- [x] 入金された金額を、この管理画面に入力していく形となる。入金の合計金額と請求残金を表示する。
- [x] 加算していって、請求金額の残高が０になったら入金済みとして、入金済みカラムをTrueにする。
- [x] 入金が請求金額よりオーバーしたら、「過入金です」とモーダルを表示する。（表示するだけで良い）
- [x] よって、備考欄上の入金済みチェックボックスはいらなくなるので、チェックボックスを削除。
- [x] 入金処理ウィンドウの支払い方法入力欄の選択肢は「口座振込」「現金」「クレジット」の３つを選択肢にする。（並び順もこの通りにして欲しいとの事）
- [x] 請求＿入金テーブルの保存タイミングは、モーダルの「OK」をクリックした時
- [x] 入金レコードを削除するボタンを作成する。通常時はグレー、ホバー時に赤。

![image](https://user-images.githubusercontent.com/77572073/160964144-a8e54c0e-4cd4-40d3-af30-d9ebefe2231f.png)

![image](https://user-images.githubusercontent.com/77572073/162128756-d623c1a0-b1aa-4e74-bda3-de11a3651921.png)

**Comment by monomonosu** [comment]
入金処理のウィンドウ。タブレットモードだと別ページとして表示される形になるからこのレイアウトではダメな気がする。
モーダルかタブ切り替えとかにしてしまった方が良い気がするな。

**Comment by monomonosu** [comment]
とりあえずモーダルで進めてみる。

**Comment by gamasenninn** [comment]
モーダルでよいと思う
