### ISSUE TITLE
得意先・商品ページで項目を編集して保存しても未保存モーダルが出てしまう

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#958]
得意先ページと商品ページの更新画面で内容を編集後に保存。その後に「＜」で戻ろうとすると未保存モーダルがでてしまう。
アップロードファイル数管理から直接ディレクトリを見に行く方式に変えて治ったと思ったのだが。原因を調査して修正。

- [ ] 得意先
- [ ] 商品

**Comment by gamasenninn** [comment]
これはけっこう深いバグっぽい。そもそもwatchで変化をカウントする方式は不自然なような気がしてきた。保存の時に更新差分があるかどうかをチェックしたほうが自然なような気がする。なので、その方式でロジックを書き直してみる。

**Comment by gamasenninn** [comment]
差分ロジック変更につきwatchでオブジェクトの差分を監視しない形にした。
