### ISSUE TITLE
数値にマイナスが入れれてしまうのでマイナスが入らないように

### ISSUE THREAD

**Issue by monomonosu** [Crescom-SohoCaddie/soho-caddie#959]
指摘をもらったのはユーザーの任意番号にマイナスが入らないように。との事だが、他にもマイナスを入れれる箇所があるので、そこも修正するようなら修正する。

**Comment by gamasenninn** [comment]
任意番号はそれでいいが、請求書・見積書の明細はマイナスは入ったほうがいいよ。値引き処理欄がないから、マイナス数値で値引き調整しないとならんでしょ？

**Comment by monomonosu** [comment]
おお、なるほど。確かにその通りだ。
ユーザーの任意番号以外にも得意先にも任意番号が付く予定なので、とりあえず任意番号のみマイナスが入らないようにするだけで良いかもしれないな。

**Comment by gamasenninn** [comment]
そうだね
